apiVersion: apps/v1
kind: Deployment
metadata:
  name: wedding-gallery-backend
  labels:
    app: wedding-gallery-backend
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: wedding-gallery-backend
  template:
    metadata:
      labels:
        app: wedding-gallery-backend
    spec:
      imagePullSecrets:
        - name: dockerconfigjson-ghcr
      initContainers:
        - command:
          - /app/init_start.sh
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                key: database-url
                name: wedding-gallery-secret
          - name: DIRECTORY
            value: ./files
          - name: HOST
            value: "0.0.0.0"
          - name: PORT
            value: "1080"
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: "{{ .Values.backend.image.pullPolicy }}"
          name: wedding-gallery-init
          resources: {}
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /app/files
              name: wedding-gallery-store
            - mountPath: /app/caches
              name: wedding-gallery-caches
      containers:
        - env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                key: database-url
                name: wedding-gallery-secret
          - name: DIRECTORY
            value: ./files
          - name: HOST
            value: "0.0.0.0"
          - name: PORT
            value: "1080"
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: "{{ .Values.backend.image.pullPolicy }}"
          name: wedding-gallery-backend
          resources: {}
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /app/files
              name: wedding-gallery-store
            - mountPath: /app/caches
              name: wedding-gallery-caches
      volumes:
        - name: wedding-gallery-store
          persistentVolumeClaim:
            claimName: wedding-gallery-store
        - name: wedding-gallery-caches
          persistentVolumeClaim:
            claimName: wedding-gallery-caches
      restartPolicy: Always