apiVersion: v1
kind: PersistentVolume
metadata:
  name: wedding-gallery-store
spec:
  storageClassName: ""
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data-pool/Wedding_Public
    server: 10.0.1.99
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wedding-gallery-caches
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /rpool/home-cluster/wedding-gallery-caches
    server: 10.0.1.99
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wedding-gallery-db
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /rpool/home-cluster/wedding-gallery-db
    server: 10.0.1.99
    readOnly: false