apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wedding-gallery-store
spec:
  storageClassName: ""
  volumeName: wedding-gallery-store
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wedding-gallery-caches
spec:
  storageClassName: ""
  volumeName: wedding-gallery-caches
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wedding-gallery-db
spec:
  storageClassName: ""
  volumeName: wedding-gallery-db
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi