apiVersion: v1
kind: Secret
metadata:
  name: wedding-gallery-secret
type: Opaque
data:
  database-url: "{{ .Values.secrets.database_url | toString | b64enc }}"
  postgres-password: "{{ .Values.secrets.postgres_password | toString | b64enc }}"