apiVersion: v1
kind: PersistentVolume
metadata:
  name: miner-analytics
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /rpool/home-cluster/channelpointminer/analytics
    server: 10.0.1.99
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: miner-cookies
spec:
  storageClassName: ""
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /rpool/home-cluster/channelpointminer/cookies
    server: 10.0.1.99
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: miner-logs
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /rpool/home-cluster/channelpointminer/logs
    server: 10.0.1.99
    readOnly: false