apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miner-analytics
spec:
  storageClassName: ""
  volumeName: miner-analytics
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miner-cookies
spec:
  storageClassName: ""
  volumeName: miner-cookies
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: miner-logs
spec:
  storageClassName: ""
  volumeName: miner-logs
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi