apiVersion: v1
kind: Secret
metadata:
  name: point-miner-secret
type: Opaque
data:
  telegram-chatid: "{{ .Values.secrets.telegram.chat_id | toString | b64enc }}"
  telegram-token: "{{ .Values.secrets.telegram.token | toString | b64enc }}"
  discord-webhook: "{{ .Values.secrets.discord.webhook | toString | b64enc }}"