apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rutorrent-config
spec:
  storageClassName: ""
  volumeName: rutorrent-config
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rutorrent-data
spec:
  storageClassName: ""
  volumeName: rutorrent-data
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Ti