apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-proxy
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
    - port: 8081
      targetPort: 8081
      protocol: TCP
    - port: 8082
      targetPort: 8082
      protocol: TCP
  type: ClusterIP
