apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-proxy
  ports:
    - port: 8080
      targetPort: 8080
      name: http-tcp
      protocol: TCP
  type: ClusterIP
