apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mosquitto
  name: mosquitto
spec:
  type: NodePort
  selector:
    app: mosquitto
  ports:
  - port: 1883
    nodePort: 30000
    targetPort: 1883
    protocol: TCP
    name: default
  - port: 9001
    nodePort: 30001
    targetPort: 9001
    protocol: TCP
    name: websocket
