apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - secretName: jellyfin-tls
      hosts:
        - plexserver.picturo.us
  rules:
    - host: plexserver.picturo.us
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyfin-tcp
                port:
                  name: http-tcp