apiVersion: ENC[AES256_GCM,data:9Cg=,iv:vyDpSHOHkmPrfto76rOCDqLzR3A5wDpfcd4OMPViEnM=,tag:nWyRZKgUzbVPNistunJQMA==,type:str]
kind: ENC[AES256_GCM,data:JWQbA9+T,iv:+NHnBZyz2GlMMfY+l9QxXKBzGm3pu93EcrB+jR0uDkg=,tag:2QVL/qJAXM0Xf2+D4ueU7g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:sFR2D30jZUg3rqz1d6qaQvHc7FW78g==,iv:xHGgNf8HQId6loq6wA53NlcTM1MqwJiIquWl+KoH25E=,tag:w5sd05qIRygzptmnrK3Ibw==,type:str]
    namespace: ENC[AES256_GCM,data:Y5QmGS/OnAj6csYWE6BG,iv:bO6k9Jrp4C5S0phQSUk4uWtGwUNbtYKsGibKGlCR2PU=,tag:T+QiJqDUXxdBvED8ut/JLw==,type:str]
type: ENC[AES256_GCM,data:8l+EDa8P,iv:pdX8stUUkwOiCnjN3BTYJrqdWvXsOxSCkmzXuzUDreg=,tag:wnqXfQc7MzABNBhNIjzglA==,type:str]
data:
    DEV_GUILD_ID: ENC[AES256_GCM,data:Gc0RDE/N0C2gzKyhIjFwEk2R,iv:hQYdxvZQnXyNhGgpEslIZjlifXv8q7D5S0gXH+RlWfs=,tag:rEsEogz3xQoqAUGqUYF1ug==,type:int]
    DISCORD_TOKEN: ENC[AES256_GCM,data:Ad2omFJOL7jFgkL33IgwZAA59K4clMe7pm0GYXS/nriLgm2ZxrCFsZAl8WoylmPmZF+rTvDcj6eO85Q=,iv:9hUmzEaxT9DtALcwLFnXrAWJUVqq3jDyVKX7o+y1h90=,tag:TzfhBWuuBEHxqQJK+dnEIQ==,type:str]
    DISCORD_CLIENT_ID: ENC[AES256_GCM,data:L+UhAIziFjk6/Eq4orx+JDci,iv:nD+CIzOqO2U7wEezStsdXl8Z5adGNA1NhuT8KYJEvss=,tag:vgSuVajuQl0tek3bM5HSeg==,type:int]
    DISCORD_CLIENT_SECRET: ENC[AES256_GCM,data:F/7ELAOXd3CFUd62KJis3lYdmMfMdou+bdo/i+fUO30=,iv:0aL9pbzObghzUC/hrBKhNifqft9Z+c8Vq/U5UER+7MU=,tag:kQn0uVk0pqgY43rHGORUCQ==,type:str]
    DISCORD_BOTLOG_CHANNEL: ENC[AES256_GCM,data:QcVU64o/Z7XCh3XFIwYT2B4V,iv:/aD40u4vxtXKnnFBYyiWfODP2FCgNZgEoJPt7veA9A8=,tag:KhfnNWkGr1r+ZbpIacRqHw==,type:int]
    DISCORD_ANNOUNCE_CHANNEL: ENC[AES256_GCM,data:4AdOGuOAVvCUZ0ejFObTHJa8,iv:yRlaLDq2BFqieHlJHBC1aQVE2XEYNlAAfB7+mBp8XtI=,tag:m9HITC+8gsUT9134C+DVTQ==,type:int]
    SUPABASE_URL: ENC[AES256_GCM,data:lPuxHl4SNcqLOplVaiNwcbODvUxFZJ6yhDytRdc+fHtXx8N1tlwWQw==,iv:JRTsl0gYM8VgdLAtPdu4jzGRG504PrEeA3r17Kfk2VU=,tag:tZfxnpY7HzxxkBeVPTNLJw==,type:str]
    SUPABASE_KEY: ENC[AES256_GCM,data:C89APhdsGqRd3MO7eH1OxplD7oUgAJiV2CO4eWjPDxuH4j3YBPLd5Zi4wY4s66sGfLWoJI71BFfgVZfUH0yNwncEdRtwTGbljqQJSsG30X7sm/T3lHifO1XpIVlUY/l5cbQ3tYrv4IWBojyzPO4onzDzih9cqBEydi0EW9cHhOcLETWvDM22O4T1cdnJt/MTOYZw,iv:3dcoDlZET0VitckxgPLpoNfUEVGtpqAmDBMoxA4H12c=,tag:75tuojcVX3XU27ym7BbWpw==,type:str]
    TABLE: ENC[AES256_GCM,data:TNlIYm0losVBdrNDJic1/1o1,iv:ml3h9r2ab9XdWl0xChF6to4mxOABHHPcmfEeEVj+Q0U=,tag:AP+D8N5S5pJCl2A4SZxnXw==,type:str]
    TWITCH_TABLE: ENC[AES256_GCM,data:/1eUVxLIuKEe/Q==,iv:Llh2X7J3cAMx89XA4WdCOMOhg/t9AdvQiN+zQaeMrn0=,tag:QEgxE0Fdaoh60l1DgS+0fg==,type:str]
    YOUTUBE_CHANNEL_ID: ENC[AES256_GCM,data:DrLvG6s+u72CCmpOrK3Y/8ijN9VId5n7,iv:74vMLdQR0O3fQXlZQnCFL27VyeqoVhVQWH7Ty7h+T7w=,tag:c0KmmZGGUVzQHPfxS7cujw==,type:str]
    ABLY_KEY: ENC[AES256_GCM,data:9atvypxwcWyP5Od6b9/F6zn+m11+bmgtr2+CGaA6,iv:C590d3hoGeu3m/opQ5PEa5/p+/aeeMXPJ2yMgZStwCE=,tag:jHMN//iS9znu6gMzqltVHw==,type:str]
    TWITCH_CALLBACK_URL: ENC[AES256_GCM,data:87A5/dga/Vk0N5Q6lF/tIx5RQIqk56Lfd2Poipj64HVF1JOc4JY0,iv:69ZKy6mpcY3+J2sjDozwcDhXYGEBhwh4O9IF6W5QkKc=,tag:3oLH2JQCxXeDUqLAnTsCvQ==,type:str]
    YOUTUBE_CALLBACK_URL: ENC[AES256_GCM,data:cXZ8u3ij3USYCVFrSzTSxTI0vmwTiNFdTKiXyDEPDWciVQ==,iv:D9s6VRQnaRf/tVQNVT33nE3zCvHzbQkZPetybpqe0Oc=,tag:jmF1y3hgeC6TnZij5h5g4Q==,type:str]
    COIN_FLIP_RATE: ENC[AES256_GCM,data:2jQ=,iv:CVsWWOEAsEvTLxLz606FPDj6zv46BIk5JY6/2o/s7Qw=,tag:mbR64rKKQMixPi/jtf5Tig==,type:int]
    COIN_FLIP_THRESHOLD: ENC[AES256_GCM,data:rHdh,iv:SwoSp6E5ck496MwY0wwVuIBT/bRGCjeixFkesyIoI3c=,tag:SdQtjD3MZOp0XUdmd/mQCw==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ywpfn53y9vnyx38mphm7v5zgrnz8ap66hmzs3rn0j2gtzqyr2grql9zvha
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNXdoU2ltWWdURmt3Mm9s
            NXhiTklQempCLzV0aXp1b0JHc3RRVmRONkFFCm93MnBBb2lzdmpkUldvL3dOMWpZ
            R3VlYlNMSnlNSlcxenZCUVNpWnNsaTgKLS0tIGdld1BBRUJoaytIWlRVNVB4elJF
            eG9seURTOXhodm5JZEt4elVkL3hVZWcKy7NDhftsAiV8vk6Ukyq4kbjFePLfWm2B
            RKIDh5qYkpJ3mVhRj6WizVBZ5M9ufTTLkO2kuAqbX2MlwpYqocac0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-03-29T17:05:55Z"
    mac: ENC[AES256_GCM,data:xGYs4xgrCcQG2+C6iaXkiAmbj90DuaJXyvv8KxxKiBCjBYLr69XHFoTQqa/IgxNtsb/cA3Fl3X5+2U12OSd/sGmqBJzhp+Z/wxGle163j6fPh1Io9v/9N80yy6AbU5XpC+21IwI3VvT/214OKd4lisgZ3tT6OR/O3IEn/Y0Hc1E=,iv:i1Xf528aq0OPSQ0tgORS2k2taFMXDXpKweReWrMn7dk=,tag:gNeXCog7siTVsngxjUHZBw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.2
