secrets:
    postgres_password: ENC[AES256_GCM,data:FiDwRWF5gFh3tNhw,iv:sEOVk+9bGhqM2uZf90CPUDjPr0HauYaS/gjWElE8ddI=,tag:xmCRjf1UQYJNVmhqfZ6Hgw==,type:str]
    ably_key: ENC[AES256_GCM,data:X0u9f4SyDa9PtsPCw8ZCyyOeMeDZDoaMwAEby+Gv,iv:I5v2qIjOuJTN0nPPyihefvet13c3Vdg7gENQ7T2SCTk=,tag:qyYdezKQxwWFO1Zx12FeLw==,type:str]
    coin_flip_rate: ENC[AES256_GCM,data:22s=,iv:iXkOBBjj/AYa9/mPuVps4w+bPatqxs7haFzf3s9PZjg=,tag:yJyoyWOEmyfEsFb8FOuquQ==,type:int]
    coin_flip_threshold: ENC[AES256_GCM,data:yQcm,iv:eHSGStsM6HuNjvsvgLu9Ma9YRykXj+TL+vZbv62yyfA=,tag:h9WJkl94fbwdKBUzpdQg2Q==,type:int]
    database_url: ENC[AES256_GCM,data:DIDpA5Bw9ta4EJjOU7+oP+hSSSHpI5NBwqx4mL67FgngTS3J6ihT5ILfPgAG9w9Gvi7KP77PzP0WaecIe9Rq,iv:lzRmGDJuCd/ghUwuNVgfjlFBIeafA0AjfMyOkFsuhBE=,tag:s/ePH8370OXA0CiG8ESJHA==,type:str]
    dev_guild_id: ENC[AES256_GCM,data:fhbT0vWZtWRrQZo7ckQq4MRO,iv:/aHkvzEnjGeFUzDU/J1uM8wLUffvl+baym/AHixV6j4=,tag:r7WwIqmdMobR2ChGrM1lhg==,type:int]
    discord_announce_channel: ENC[AES256_GCM,data:42ppybgxWrxGaPEzviIxUXyJ,iv:muzwsFqFoyEMHWXJhlXzCm3j9rtpWU7IHJdjt8CsJ5s=,tag:fF2MI7AS1jnrf/qx3rjeXg==,type:int]
    discord_botlog_channel: ENC[AES256_GCM,data:0MgTDN0yU1/dGTHCpCPy3Fw4,iv:jhX+Lu8xZBGqaaSBbQday7V2qtWFvZOK2+KZpk+80po=,tag:KqGa9TYEwmrIe5RXuJatQQ==,type:int]
    discord_client_id: ENC[AES256_GCM,data:zQxNhHVlJnToRQxF8PnEhy55,iv:ldAhCiYIOQrpwHB4YGHmApi7Wm2DbqZSnGntoZZUtCc=,tag:U8I+nx/91UXB4G/DxyQy0g==,type:int]
    discord_client_secret: ENC[AES256_GCM,data:sS38oBtJDCN5CWxc4bopEwhcuSMCt7tvofWiiyk0HCI=,iv:nFRtM/0XsNKVf2IOiADFcOlYBNrjhejv3D+DdC/s5bg=,tag:w1eBX7gLvx0O+KZlBO0HRQ==,type:str]
    discord_link: ENC[AES256_GCM,data:VSGrBp1uJKNt4Caiaz4mx2crAG4fdS/Dc7gGRnA=,iv:Qk4F/bQry5ivJOnjAg+SO7MiXyEwfJCN4m7ozyftt50=,tag:bpyqMfJs7cVWloVuwJk8pg==,type:str]
    discord_token: ENC[AES256_GCM,data:rNtlslqmhjUyl00/fcK5KnxPxhcexjIpFA5Dn5Zon/FCyQeo5oH8901bXEqz0Q0IAxKYTUvZLPX2CpHLuA/s127NAkVvaQ==,iv:HGXFYCUDPzuntv6qaHhjIeYeZoe/c6j8a791/rgXz9c=,tag:tRlCZOo4R1iPo+f5cYaAjg==,type:str]
    event_sub_secret: ENC[AES256_GCM,data:jJovpm9lUvHPvywRDjqAg70=,iv:fQxK4BK1/XBqxwu5BYLjNK04+IeMsCmPe+Jj80VjyZI=,tag:YB7eMsWv5n5nMyQQMte7Xw==,type:str]
    facebook_link: ENC[AES256_GCM,data:NdWvkdvpmlhmU/77DqT/RXiCnxmGoKzznPFFqJXbOIfomjS2,iv:yf+28sGaNdlOlZkx090b4xvnRQ53xScbRRvkXBbQvQ0=,tag:NC4dBXq1vMY/eHL2nW1k5w==,type:str]
    instagram_link: ENC[AES256_GCM,data:wzlUSIy3oRZmgwgl8N4S/BtPKNXWTWbtd2ivMYGdbq8fJA==,iv:qe2ukc0bv2uxzKZ2e2tTht89iEXfSn6fI2lPNw5zFrY=,tag:F5yaFis0atm78qYflozmZg==,type:str]
    redis_url: ENC[AES256_GCM,data:+vdi2HhMXULYeXrW9VbD0+atJSiX6pu7+SXYYtLjoy3QCQ==,iv:nE7rUUXd5GvuPgNSAyefSBu1pS7JTkG8kdxwtC0e/Bo=,tag:u2yGXdEW2wQqDP8um+7oFw==,type:str]
    tipme_link: ENC[AES256_GCM,data:Z/TKX29J4/nVP+vim81UDacM6wfRPuRkRQHixWFz,iv:bLRQFEc/7jHFkXdwAs5J7Fjqv+h19f46Oq3pRCJxCpg=,tag:TLzy/Hxmb4cj2MtbjBFMfw==,type:str]
    twitch_access_token: ENC[AES256_GCM,data:8UsRdADuUXBVWDYWKfX9SMDlfoNmGxJ1O/n977tp,iv:WPYD753xAC3zWVImXZu6J4FxAmDIo670gF7qagyaM24=,tag:7ZsgVvrNgHfItB7koG+70Q==,type:str]
    twitch_bot_nick: ENC[AES256_GCM,data:YqoOPLVAO6yLUw==,iv:59yFsL9HwmNKaWcG49ZFGz8b6EVMmopurooLxlGwvBM=,tag:0dojLJciqERYaNNJxtefvA==,type:str]
    twitch_callback_url: ENC[AES256_GCM,data:5VTrxRtFkXy5hn+dtwSPlDRODf9vjQtXi5DAGE9+uw18IPlLGaBAH9Q=,iv:Kxv1CvLm6EY2U2K/UuYIud9mx49OOycXhoT/UPFroBI=,tag:mZjMCR86MT9DxUKc8/uYMA==,type:str]
    twitch_channel_name: ENC[AES256_GCM,data:XG2hsJH0d6KSrw==,iv:71Q5mpzbeJ6taFcW8HWxmfmh5RIPwMSmuvMjD4VMzkI=,tag:iqGnTzIDg0thXX+uo1rqBw==,type:str]
    twitch_client_id: ENC[AES256_GCM,data:u2DiWL6pk6aoUSEI/gWeEbDP64IXo7hKB2CwlJl7,iv:XoboyBUPjURaRE5XjLyGow140WrS3haSZQnEQ81hblc=,tag:ivvRMYhAWRB/SFVt0kaHWA==,type:str]
    twitch_http_client_id: ENC[AES256_GCM,data:8jNNdrKjo1BPV0JKDwFhZOBMPblVnvERF92MJ2lE,iv:SJ+Yc2YIiIqnhAmHSNJZJZ4MuQQRFz7ozu5DweNcQiY=,tag:f15sJ3H7eMCj8g9DO0HBwg==,type:str]
    twitch_http_client_secret: ENC[AES256_GCM,data:P6GNpfGv368ydp6tMoIUNFo5fCrcKUjf4IpevMgM,iv:9BUWVyNhR3/fwMl8VUOBovTpCnHoSzS0dxrq3aFnSDU=,tag:yJUxhp/MYwUmCLCb0e8TSA==,type:str]
    twitch_userid: ENC[AES256_GCM,data:JowkvlWpPyyJ,iv:kWifQb+jg7hDV6vcQZtJ/y1oOR+Q/1Sl/4wpz8eGCPA=,tag:4Pz4sqVFcGj52SQDpPnhOA==,type:int]
    youtube_callback_url: ENC[AES256_GCM,data:zXJIN0bA2f+SMpBp4ON+FAMG/Mv7994LUt3b+x7Ab/7s8DwC,iv:ij4hu1aO+1pLW+9lQJ1AzqTp5saXR5z1HkDncimEfh4=,tag:udB+F0sMutJcWcZNbYzYjg==,type:str]
    youtube_channel_id: ENC[AES256_GCM,data:t3A/zCk+9ZQKz+O+tuh6h2v/6PsnlwI1,iv:hbAI6B6lJJv8yc7bYoxmK9Jo8obQZmE6/JwbCRsUlUc=,tag:KH/xQwEfhJda9y+rNcFrpw==,type:str]
    youtube_link: ENC[AES256_GCM,data:TF8dEh2ShuTeYa2SUQmg93X7EKSgOPIXQECLu73JhJyCRw==,iv:AJgTVa00bnUcHDvy9u20jjMR4D4gOXN2uREERU2YWas=,tag:7aTA48Xo8w1kfEIgmDRERQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16n5tg0lu2gqwmzcy807dy9jam37v0vash2w6z65cgc5qcyslef4sjd6we3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKNzRab1o1YUJWNEtoR0JT
            MHkvd3c4aHRwSFBxM2t3eXRpbG81bjBwVkFjCmRxOSs2N2hLWjkzQ3YvaHNEWEVx
            bnFnN1pYN3RkU3dMT3FteWF4cE9BYzQKLS0tIHo0dWg3TkYrSU1EN1ZRbUhuNnpP
            dkRtYjlsTTB0dFpNSzF1OXB6YTJXMEkKz6LLQD2p0XYmtj7sha7sP+oB+G7lh4rR
            jmR1+1Msqbm74eIXH+N4/X6Aox0xW9OtPveRfzfjZsUnqG75ytiJiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-31T15:43:14Z"
    mac: ENC[AES256_GCM,data:7MpoCKiIB9NAh6iv1Zt/dH1zeJlk1z6Sd8F58mX18eE8nqk2t/n7WhlUXhcxjh1ZUNBy7UUphINH+lBtt8X1FJq4CS3CAwHgg0QDw2of/TrN3Ylcxp0sO+S+Bpsc8sIABOsKvX3n8yNReIwzEtzsaJNGpuP9Sb9yEKx7EZDRsoA=,iv:NPpxzY6ZqwIsxB24IfJZRMOx1A3IJWPorJjeG+yklUs=,tag:pogVbd81nc/6fdHFtfjRSw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
