apiVersion: apps/v1
kind: Deployment
metadata:
  name: autohls
  labels:
    app: autohls
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: autohls
  template:
    metadata:
      labels:
        app: autohls
    spec:
      imagePullSecrets:
        - name: dockerconfigjson-ghcr
      containers:
        - env:
          - name: SOURCE
            value: "/source/"
          - name: DEST
            value: "/dest/"
          - name: PORT
            value: "4000"
          - name: CORSHOST
            value: "https://vodstatus.picturo.us"
          - name: PUBLIC_SOCKET_URL
            value: "https://vodstatus.picturo.us/socket"
          - name: PROJECT_ID
            valueFrom:
              secretKeyRef:
                key: PROJECT_ID
                name: autohls-secret
          - name: TOPIC_NAME
            valueFrom:
              secretKeyRef:
                key: TOPIC_NAME
                name: autohls-secret
          - name: SUBSCRIPTION_NAME
            valueFrom:
              secretKeyRef:
                key: SUBSCRIPTION_NAME
                name: autohls-secret
          - name: CLIENT_EMAIL
            valueFrom:
              secretKeyRef:
                key: CLIENT_EMAIL
                name: autohls-secret
          - name: PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                key: PRIVATE_KEY
                name: autohls-secret
          - name: SUBJECT
            valueFrom:
              secretKeyRef:
                key: SUBJECT
                name: autohls-secret
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                key: DATABASE_URL
                name: autohls-secret
          - name: DIRECT_URL
            valueFrom:
              secretKeyRef:
                key: DIRECT_URL
                name: autohls-secret
          # securityContext:
          #   runAsUser: 65534
          #   runAsGroup: 100
          #   allowPrivilegeEscalation: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          name: autohls
          resources:
            requests:
              gpu.intel.com/i915: "1"
            limits:
              gpu.intel.com/i915: "1"
          volumeMounts:
            - mountPath: /source
              name: autohls-source
            - mountPath: /dest
              name: autohls-dest
      volumes:
        - name: autohls-source
          persistentVolumeClaim:
            claimName: autohls-source
        - name: autohls-dest
          persistentVolumeClaim:
            claimName: autohls-dest
      restartPolicy: Always