apiVersion: v1
kind: PersistentVolume
metadata:
  name: autohls-source
spec:
  storageClassName: ""
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/disks/CacheDrive/recordings
    server: 10.0.1.201
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: autohls-dest
spec:
  storageClassName: ""
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/disks/SlowPhatty
    server: 10.0.1.201
    readOnly: false