apiVersion: v1
kind: PersistentVolume
metadata:
  name: autohls-source
spec:
  storageClassName: ""
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data-pool/JibriRecordings
    server: 10.0.1.99
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: autohls-dest
spec:
  storageClassName: ""
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data-pool/VOD
    server: 10.0.1.99
    readOnly: false