apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autohls-source
spec:
  storageClassName: ""
  volumeName: autohls-source
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autohls-dest
spec:
  storageClassName: ""
  volumeName: autohls-dest
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Ti