apiVersion: v1
kind: Secret
metadata:
  name: autohls-secret
type: Opaque
data:
  PROJECT_ID: "{{ .Values.secrets.PROJECT_ID | toString | b64enc }}"
  TOPIC_NAME: "{{ .Values.secrets.TOPIC_NAME | toString | b64enc }}"
  SUBSCRIPTION_NAME: "{{ .Values.secrets.SUBSCRIPTION_NAME | toString | b64enc }}"
  CLIENT_EMAIL: "{{ .Values.secrets.CLIENT_EMAIL | toString | b64enc }}"
  PRIVATE_KEY: "{{ .Values.secrets.PRIVATE_KEY | b64enc }}"
  SUBJECT: "{{ .Values.secrets.SUBJECT | toString | b64enc }}"
  DATABASE_URL: "{{ .Values.secrets.DATABASE_URL | toString | b64enc }}"
  DIRECT_URL: "{{ .Values.secrets.DIRECT_URL | toString | b64enc }}"
