apiVersion: v1
kind: Service
metadata:
  name: autohls
spec:
  selector:
    app: autohls
  ports:
    - port: 3000
      targetPort: 3000
      name: http-web
      protocol: TCP
    - port: 4000
      targetPort: 4000
      name: http-socket
      protocol: TCP
  type: ClusterIP