apiVersion: v1
kind: ConfigMap
metadata:
  name: homebridge-config
  labels:
    app: homebridge
data:
  startup.sh: |-
    #!/bin/sh

    npm install homebridge-info homebridge-config-ui-x homebridge-camera-ui homebridge-http-notification-server homebridge-http-humidity-sensor homebridge-http-temperature-sensor homebridge-tuya-ir homebridge-z2m
