apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: homebridge
  name: homebridge
spec:
  ports:
    - name: homebridge
      port: 8581
      targetPort: http
      protocol: TCP
  selector:
    app: homebridge
status:
  loadBalancer: {}
