apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
    - resources-finalizers.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: "{{ .Values.spec.destination.server }}"
  project: argocd
  source:
    path: charts/argo-cd
    repoURL: "{{ .Values.repo.url }}"
    targetRevision: "{{ .Values.repo.revision }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
