apiVersion: agroproj.io/v1alpha1
kind: Application
metadata:
  name: root
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: "{{ .Values.spec.destination.server }}"
    namespace: argocd
  project: default
  source:
    path: apps/
    repoURL: "{{ .Values.repo.url }}"
    targetRevision: "{{ .Values.repo.revision }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
