apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-helm
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: apps
    server: "{{ .Values.spec.destination.server }}"
  project: apps
  source:
    path: apps/
    repoURL: "{{ .Values.spec.repo.url }}"
    targetRevision: "{{ .Values.spec.repo.revision }}"
    helm:
      valueFiles:
        - values.yaml
        - secrets+age-import:///helm-secrets-private-keys/key.txt?secret-values.enc.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
