apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zigbee2mqtt
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: zigbee2mqtt
    server: "{{ .Values.spec.destination.server }}"
  project: default
  source:
    path: apps/zigbee2mqtt
    repoURL: "{{ .Values.repo.url }}"
    targetRevision: "{{ .Values.repo.revision }}"
    helm:
      valueFiles: {}
        # - secrets+age-import:///helm-secrets-private-keys/key.txt?secret-values.enc.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true