apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zigbee2mqtt
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: zigbee2mqtt
    server: "{{ .Values.spec.destination.server }}"
  project: smarthome-project
  source:
    path: apps/zigbee2mqtt
    repoURL: "{{ .Values.repo.url }}"
    targetRevision: "{{ .Values.repo.revision }}"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
