apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hoobs
  name: hoobs
spec:
  type: NodePort
  selector:
    app: hoobs
  ports:
  - port: 80
    nodePort: 30005
    targetPort: 80
    protocol: TCP
    name: default
  - port: 30004
    nodePort: 30004
    targetPort: 30004
    name: bridge
