apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hoobs
  name: hoobs
spec:
  type: NodePort
  selector:
    app: hoobs
  ports:
  - port: 8080
    nodePort: 30005
    targetPort: 8080
    protocol: TCP
    name: default
