apiVersion: v1
kind: PersistentVolume
metadata:
  name: streaming-tools-db
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /rpool/home-cluster/streaming-tools-db
    server: 10.0.1.99
    readOnly: false