apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streaming-tools-db
spec:
  storageClassName: ""
  volumeName: streaming-tools-db
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi