apiVersion: v1
kind: Secret
metadata:
  name: streaming-tools-secret
type: Opaque
data:
  postgres-password: "{{ .Values.secrets.postgres_password | toString | b64enc }}"
  ably-key: "{{ .Values.secrets.ably_key | toString | b64enc }}"
  coin-flip-rate: "{{ .Values.secrets.coin_flip_rate | toString | b64enc }}"
  coin-flip-threshold: "{{ .Values.secrets.coin_flip_threshold | toString | b64enc }}"
  database-url: "{{ .Values.secrets.database_url | toString | b64enc }}"
  dev-guild-id: "{{ .Values.secrets.dev_guild_id | print | toString | b64enc }}"
  discord-announce-channel: "{{ .Values.secrets.discord_announce_channel | print | toString | b64enc }}"
  discord-botlog-channel: "{{ .Values.secrets.discord_botlog_channel | print | toString | b64enc }}"
  discord-client-id: "{{ .Values.secrets.discord_client_id | print | toString | b64enc }}"
  discord-client-secret: "{{ .Values.secrets.discord_client_secret | toString | b64enc }}"
  discord-link: "{{ .Values.secrets.discord_link | toString | b64enc }}"
  discord-token: "{{ .Values.secrets.discord_token | toString | b64enc }}"
  event-sub-secret: "{{ .Values.secrets.event_sub_secret | toString | b64enc }}"
  facebook-link: "{{ .Values.secrets.facebook_link | toString | b64enc }}"
  instagram-link: "{{ .Values.secrets.instagram_link | toString | b64enc }}"
  redis-url: "{{ .Values.secrets.redis_url | toString | b64enc }}"
  tipme-link: "{{ .Values.secrets.tipme_link | toString | b64enc }}"
  twitch-access-token: "{{ .Values.secrets.twitch_access_token | toString | b64enc }}"
  twitch-bot-nick: "{{ .Values.secrets.twitch_bot_nick | toString | b64enc }}"
  twitch-callback-url: "{{ .Values.secrets.twitch_callback_url | toString | b64enc }}"
  twitch-channel-name: "{{ .Values.secrets.twitch_channel_name | toString | b64enc }}"
  twitch-client-id: "{{ .Values.secrets.twitch_client_id | toString | b64enc }}"
  twitch-http-client-id: "{{ .Values.secrets.twitch_http_client_id | toString | b64enc }}"
  twitch-http-client-secret: "{{ .Values.secrets.twitch_http_client_secret | toString | b64enc }}"
  twitch-userid: "{{ .Values.secrets.twitch_userid | print | toString | b64enc }}"
  youtube-callback-url: "{{ .Values.secrets.youtube_callback_url | toString | b64enc }}"
  youtube-channel-id: "{{ .Values.secrets.youtube_channel_id | toString | b64enc }}"
  youtube-link: "{{ .Values.secrets.youtube_link | toString | b64enc }}"