apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app: shinobi-main
  name: shinobi-main
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: hikvisionserver.picturo.us
      http:
        paths:
          - backend:
              serviceName: shinobi-main
              servicePort: 8080
