apiVersion: v1
kind: PersistentVolume
metadata:
  name: shinobi-main-video
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 470Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    path: /mnt/disks/IPCAM
    server: 10.0.1.201
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: shinobi-main-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/shinobi-main-data"