apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: shinobi-main
  name: shinobi-main
  annotations:
    metallb.universe.tf/address-pool: private
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: shinobi-main
