secrets:
    qbittorrent_password: ENC[AES256_GCM,data:PMh5DIuqC6uViGIz,iv:kegY7zknexYqTfO3Z1nzlnIpXQROGT/T7Ctiak5jr28=,tag:TQRvhWP2jN8Rs+vsaAkWcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16n5tg0lu2gqwmzcy807dy9jam37v0vash2w6z65cgc5qcyslef4sjd6we3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAydjR1bEhVWE96cHdtaUtO
            L0tvR2JHRnRUemdsRm1uNmF6K1VKbnlvR3lvCmNDcE1RaU93Nk5rV3BGazNPSk0w
            dnQxbzVualNocHZObVVOdGdlUkUxZU0KLS0tIHk0eTdDTzMzRTBOZ3hPSnpZTFNK
            QnRpTnVVVjBJcFdFVUhPMXZEQkF4MkUKNeJyzn/bYv5YTm1A30nY0g84q58NOXZ4
            BGDFpNsVpbl+m2/a4/2V7Tq3eXUYA1LIqjlrfY6U+j5thEWevq2apA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-10T05:22:58Z"
    mac: ENC[AES256_GCM,data:aj11jMHDhhwMewbqjX0jewrq/dvdwshmVh3MTeAzRhbMkt0FLghHSVPfycnT8T19raZNVvJK0z0XMIRF9WETFWrzRwSyf21NFkQYE5cyy93yyA7GxsUlBgsw/sdkDFAcET6wUI8Di43e/zLwbEA28uhktKQaQG+VmFI0o83VZk4=,iv:/PwMLqOw+WIb7/cgSZH7C0lyDe32E+iZr2BbE0a4vSo=,tag:urPgOATzKdrzSkHxqKrHVQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
