apiVersion: v1
kind: PersistentVolume
metadata:
  name: ttb-receipt-db
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /rpool/home-cluster/ttbreceipt-db
    server: 10.0.1.99
    readOnly: false