apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ttb-receipt-db
spec:
  storageClassName: ""
  volumeName: ttb-receipt-db
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi