apiVersion: v1
kind: PersistentVolume
metadata:
  name: supapanya-vod-config
spec:
  storageClassName: ""
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /rpool/home-cluster/supapanya-vod
    server: 10.0.1.99
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: supapanya-vod-store
spec:
  storageClassName: ""
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data-pool/VOD
    server: 10.0.1.99
    readOnly: false