apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supapanya-vod-config
spec:
  storageClassName: ""
  volumeName: supapanya-vod-config
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supapanya-vod-store
spec:
  storageClassName: ""
  volumeName: supapanya-vod-store
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Ti