apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-db
  labels:
    app: taiga-db
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: taiga-db
  template:
    metadata:
      labels:
        app: taiga-db
    spec:
      containers:
        - env:
          - name: POSTGRES_DB
            value: taiga
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: postgres-password
                name: taiga-secret
          - name: POSTGRES_USER
            value: taiga
          livenessProbe:
            exec:
              command:
                - pg_isready -U taiga
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          imagePullPolicy: "{{ .Values.db.image.pullPolicy }}"
          name: taiga-db
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: taiga-db-data
      volumes:
        - name: taiga-db-data
          persistentVolumeClaim:
            claimName: taiga-db-data
      restartPolicy: Always