apiVersion: apps/v1
kind: Deployment
metadata:
  name: taiga-events
  labels:
    app: taiga-events
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: taiga-events
  template:
    metadata:
      labels:
        app: taiga-events
    spec:
      containers:
        - env:
          - name: RABBITMQ_PASS
            valueFrom:
              secretKeyRef:
                key: rabbitmq-password
                name: taiga-secret
          - name: RABBITMQ_USER
            value: taiga
          - name: TAIGA_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: taiga-secret-key
                name: taiga-secret
          image: "{{ .Values.events.image.repository }}:{{ .Values.events.image.tag }}"
          imagePullPolicy: "{{ .Values.events.image.pullPolicy }}"
          name: taiga-events
          resources: {}
      restartPolicy: Always