apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taiga-static-data
spec:
  storageClassName: ""
  volumeName: taiga-static-data
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taiga-media-data
spec:
  storageClassName: ""
  volumeName: taiga-media-data
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taiga-async-rabbitmq-data
spec:
  storageClassName: ""
  volumeName: taiga-async-rabbitmq-data
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taiga-events-rabbitmq-data
spec:
  storageClassName: ""
  volumeName: taiga-events-rabbitmq-data
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taiga-db-data
spec:
  storageClassName: ""
  volumeName: taiga-db-data
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi