apiVersion: v1
kind: Secret
metadata:
  name: taiga-secret
type: Opaque
data:
  email-host-password: "{{ .Values.secrets.EMAIL_HOST_PASSWORD | toString | b64enc }}"
  postgres-password: "{{ .Values.secrets.POSTGRES_PASSWORD | toString | b64enc }}"
  rabbitmq-erlang-cookie: "{{ .Values.secrets.RABBITMQ_ERLANG_COOKIE | toString | b64enc }}"
  rabbitmq-password: "{{ .Values.secrets.RABBITMQ_PASSWORD | toString | b64enc }}"
  taiga-secret-key: "{{ .Values.secrets.TAIGA_SECRET_KEY | toString | b64enc }}"