apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /rpool/home-cluster/qbittorrent
    server: 10.0.1.99
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-data
spec:
  storageClassName: ""
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data-pool/Movies
    server: 10.0.1.99
    readOnly: false