apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-frigate-config
spec:
  storageClassName: ""
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/home-frigate/config
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - dockerhost
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-frigate-data
spec:
  storageClassName: ""
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/disks/IPCAM/home-frigate
    server: 10.0.1.201
    readOnly: false