apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-frigate-config
spec:
  volumeName: home-frigate-config
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-frigate-data
spec:
  volumeName: home-frigate-data
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Ti