apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: autogacha
  name: autogacha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autogacha
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: autogacha
    spec:
      containers:
        - name: autogacha
          image: ghcr.io/bossoq/autogacha:1.6
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: autogacha-data
              mountPath: /app/data
      volumes:
        - name: autogacha-data
          persistentVolumeClaim:
            claimName: autogacha-data
