apiVersion: v1
kind: Service
metadata:
  name: supapanya-frigate
spec:
  selector:
    app: supapanya-frigate
  ports:
    - port: 5000
      targetPort: 5000
      name: http-web
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: supapanya-frigate-nodeport
spec:
  selector:
    app: supapanya-frigate
  ports:
    - port: 31211
      targetPort: 31211
      nodePort: 31211
      name: rtsp
      protocol: TCP
    - port: 1935
      targetPort: 1935
      nodePort: 31212
      name: rtmp
      protocol: TCP
    - port: 31213
      targetPort: 31213
      nodePort: 31213
      name: go2rtc-tcp
      protocol: TCP
    - port: 31213
      targetPort: 31213
      nodePort: 31213
      name: go2rtc-udp
      protocol: UDP
  type: NodePort