apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: zigbee2mqtt
  name: zigbee2mqtt-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
status: {}
