apiVersion: v1
kind: PersistentVolume
metadata:
  name: managerio-data
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /rpool/home-cluster/managerio
    server: 10.0.1.99
    readOnly: false