apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: managerio-data
spec:
  storageClassName: ""
  volumeName: managerio-data
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi