apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jitsi
  # annotations:
  #   argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: "{{ .Values.spec.destination.server }}"
  project: default
  source:
    path: ""
    repoURL: "https://jitsi-contrib.github.io/jitsi-helm"
    targetRevision: "1.3.8"
    chart: jitsi-meet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true