apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jitsi-jibri-config
spec:
  storageClassName: ""
  volumeName: jitsi-jibri-config
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jitsi-jibri-recordings
spec:
  storageClassName: ""
  volumeName: jitsi-jibri-recordings
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Ti