apiVersion: v1
kind: PersistentVolume
metadata:
  name: jitsi-jibri-config
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /rpool/home-cluster/jitsi/jibri
    server: 10.0.1.99
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jitsi-jibri-recordings
spec:
  storageClassName: ""
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data-pool/JibriRecordings
    server: 10.0.1.99
    readOnly: false