apiVersion: v1
kind: PersistentVolume
metadata:
  name: jitsi-jibri-config
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/jitsi/jibri
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - dockerhost
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jitsi-jibri-recordings
spec:
  storageClassName: ""
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/disks/CacheDrive/recordings
    server: 10.0.1.201
    readOnly: false