apiVersion: v1
kind: PersistentVolume
metadata:
  name: jitsi-jicofo-config
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /rpool/home-cluster/jitsi/jicofo
    server: 10.0.1.99
    readOnly: false