apiVersion: v1
kind: Secret
metadata:
  name: jitsi-secret
type: Opaque
data:
  jibri-recorder-password: "{{ .Values.secrets.JITSI_JIBRI_RECORDER_PASSWORD | toString | b64enc }}"
  jibri-xmpp-password: "{{ .Values.secrets.JITSI_JIBRI_XMPP_PASSWORD | toString | b64enc }}"
  jicofo-auth-password: "{{ .Values.secrets.JITSI_JICOFO_AUTH_PASSWORD | toString | b64enc }}"
  jicofo-component-secret: "{{ .Values.secrets.JITSI_JICOFO_COMPONENT_SECRET | toString | b64enc }}"
  jvb-auth-password: "{{ .Values.secrets.JITSI_JVB_AUTH_PASSWORD | toString | b64enc }}"
  jwt-app-secret: "{{ .Values.secrets.JITSI_JWT_APP_SECRET | toString | b64enc }}"