apiVersion: v1
kind: Service
metadata:
  name: jitsi-jvb
spec:
  selector:
    app: jitsi-jvb
  ports:
    - port: 9090
      targetPort: 9090
      name: http-jvb
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: jitsi-jvb-nodeport
spec:
  selector:
    app: jitsi-jvb
  ports:
    - port: 30000
      targetPort: 30000
      nodePort: 30000
      name: jvb-rtp
      protocol: UDP
    - port: 32443
      targetPort: 32443
      nodePort: 32443
      name: jvb-ws
      protocol: TCP
  type: NodePort