apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jitsi-jvb-config
spec:
  storageClassName: ""
  volumeName: jitsi-jvb-config
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi