apiVersion: v1
kind: PersistentVolume
metadata:
  name: jitsi-prosody-config
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /rpool/home-cluster/jitsi/prosody/config
    server: 10.0.1.99
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jitsi-prosody-plugins
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /rpool/home-cluster/jitsi/prosody/prosody-plugins-custom
    server: 10.0.1.99
    readOnly: false