apiVersion: apps/v1
kind: Deployment
metadata:
  name: jitsi-prosody
  labels:
    app: jitsi-prosody
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: jitsi-prosody
  template:
    metadata:
      labels:
        app: jitsi-prosody
    spec:
      imagePullSecrets:
        - name: dockerconfigjson-ghcr
      containers:
        - env:
          - name: AUTH_TYPE
            value: jwt
          - name: ENABLE_AUTH
            value: "1"
          - name: ENABLE_IPV6
            value: "0"
          - name: ENABLE_LOBBY
            value: "1"
          - name: ENABLE_RECORDING
            value: "1"
          - name: JIBRI_RECORDER_PASSWORD
            valueFrom:
              secretKeyRef:
                key: jibri-recorder-password
                name: jitsi-secret
          - name: JIBRI_RECORDER_USER
            value: recorder
          - name: JIBRI_XMPP_PASSWORD
            valueFrom:
              secretKeyRef:
                key: jibri-xmpp-password
                name: jitsi-secret
          - name: JIBRI_XMPP_USER
            value: jibri
          - name: JICOFO_AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                key: jicofo-auth-password
                name: jitsi-secret
          - name: JICOFO_AUTH_USER
            value: focus
          - name: JICOFO_COMPONENT_SECRET
            valueFrom:
              secretKeyRef:
                key: jicofo-component-secret
                name: jitsi-secret
          - name: JVB_AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                key: jvb-auth-password
                name: jitsi-secret
          - name: JVB_AUTH_USER
            value: jvb
          - name: JWT_APP_ID
            value: supapanya_jitsi_app
          - name: JWT_APP_SECRET
            valueFrom:
              secretKeyRef:
                key: jwt-app-secret
                name: jitsi-secret
          - name: PUBLIC_URL
            value: https://meet.supapanya.com
          - name: TZ
            value: Asia/Bangkok
          - name: XMPP_AUTH_DOMAIN
            value: auth.meet.supapanya.com
          - name: XMPP_DOMAIN
            value: meet.supapanya.com
          - name: XMPP_GUEST_DOMAIN
            value: guest.meet.supapanya.com
          - name: XMPP_INTERNAL_MUC_DOMAIN
            value: internal-muc.meet.supapanya.com
          - name: XMPP_INTERNAL_MUC_MODULES
          - name: XMPP_MODULES
            value: token_affiliation,token_owner_party,token_verification,muc_census
          - name: XMPP_MUC_DOMAIN
            value: muc.meet.supapanya.com
          - name: XMPP_MUC_MODULES
          - name: XMPP_PORT
            value: "5222"
          - name: XMPP_RECORDER_DOMAIN
            value: recorder.meet.supapanya.com
          image: "{{ .Values.prosody.image.repository }}:{{ .Values.prosody.image.tag }}"
          imagePullPolicy: "{{ .Values.prosody.image.pullPolicy }}"
          name: jitsi-prosody
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: jitsi-prosody-config
            - mountPath: /prosody-plugins-custom
              name: jitsi-prosody-plugins
      volumes:
        - name: jitsi-prosody-config
          persistentVolumeClaim:
            claimName: jitsi-prosody-config
        - name: jitsi-prosody-plugins
          persistentVolumeClaim:
            claimName: jitsi-prosody-plugins
      restartPolicy: Always