apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jitsi-web-config
spec:
  storageClassName: ""
  volumeName: jitsi-web-config
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jitsi-web-crontabs
spec:
  storageClassName: ""
  volumeName: jitsi-web-crontabs
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jitsi-web-transcripts
spec:
  storageClassName: ""
  volumeName: jitsi-web-transcripts
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi