apiVersion: v1
kind: PersistentVolume
metadata:
  name: jitsi-web-config
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /rpool/home-cluster/jitsi/web
    server: 10.0.1.99
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jitsi-web-crontabs
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /rpool/home-cluster/jitsi/web/crontabs
    server: 10.0.1.99
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jitsi-web-transcripts
spec:
  storageClassName: ""
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /rpool/home-cluster/jitsi/transcripts
    server: 10.0.1.99
    readOnly: false