# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: gpu-aware-scheduling
#   namespace: argocd
#   labels:
#     app: gas
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: gas
#   template:
#     metadata:
#       labels:
#         app: gas
#     spec:
#       serviceAccountName: gpu-aware-scheduling-service-account
#       containers:
#       - name: gasext
#         command:
#         - "/extender"
#         - "--cert=/gas/cert/tls.crt"
#         - "--key=/gas/cert/tls.key"
#         - "--cacert=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
#         - "--burst=100"
#         - "--qps=50"
#         - "--v=4"
#         image: intel/gpu-extender
#         imagePullPolicy: IfNotPresent
#         securityContext:
#           capabilities:
#             drop:
#               - all
#           readOnlyRootFilesystem: true
#           runAsNonRoot: true
#           runAsUser: 10001
#           runAsGroup: 10001
#           allowPrivilegeEscalation: false
#           seccompProfile:
#             type: RuntimeDefault
#         volumeMounts:
#         - name: certs
#           mountPath: /gas/cert
#       volumes:
#       - name: certs
#         secret:
#           secretName: extender-secret
#       tolerations:
#       - key: node-role.kubernetes.io/master
#         operator: Exists
#       - key: node-role.kubernetes.io/control-plane
#         operator: Exists
#       affinity:
#         nodeAffinity:
#           requiredDuringSchedulingIgnoredDuringExecution:
#             nodeSelectorTerms:
#             - matchExpressions:
#               - key: node-role.kubernetes.io/control-plane
#                 operator: Exists
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: gas-handler
# rules:
# - apiGroups: [""]
#   resources: ["pods"]
#   verbs: ["get","list","watch","update","patch"]
# - apiGroups: [""]
#   resources: ["nodes"]
#   verbs: ["get", "list", "watch", "patch"]
# - apiGroups: [""] 
#   resources: ["bindings","pods/binding"]
#   verbs: ["create"]
# ---
#   apiVersion: rbac.authorization.k8s.io/v1
#   kind: ClusterRoleBinding
#   metadata:
#     name: handle-gas
#   subjects:
#     - kind: ServiceAccount
#       name: gpu-aware-scheduling-service-account
#       namespace: argocd
#   roleRef:
#     kind: ClusterRole
#     name: gas-handler
#     apiGroup: rbac.authorization.k8s.io
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: gpu-aware-scheduling-service-account
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: gas-service
#   namespace: argocd
# spec:
#   selector:
#     app: gas
#   type: ClusterIP
#   ports:
#     - port: 9001
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: extender-secret
#   namespace: argocd
# type: kubernetes.io/tls
# data:
#   tls.crt: "{{ .Values.secrets.GAS_CRT | b64enc }}"
#   tls.key: "{{ .Values.secrets.GAS_KEY | b64enc }}"