apiVersion: v1
kind: Secret
metadata:
  name: extender-secret
  namespace: argocd
type: kubernetes.io/tls
data:
  tls.crt: "{{ .Values.secrets.GAS_CRT | b64enc }}"
  tls.key: "{{ .Values.secrets.GAS_KEY | b64enc }}"