apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-operator
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: "{{ .Values.spec.destination.server }}"
  source:
    path: ""
    repoURL: "https://intel.github.io/helm-charts"
    targetRevision: 0.28.0
    chart: intel/intel-device-plugins-operator
    helm:
      parameters:
        - name: installCRDs
          value: "true"
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true