# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: intel-gpu-plugin
#   namespace: argocd
# spec:
#   destination:
#     namespace: argocd
#     server: "{{ .Values.spec.destination.server }}"
#   source:
#     path: ""
#     repoURL: "https://intel.github.io/helm-charts"
#     targetRevision: "0.28.0"
#     chart: intel-device-plugins-gpu
#     helm:
#       parameters:
#         - name: resourceManager
#           value: "true"
#         - name: sharedDevNum
#           value: "10"
#   project: infra
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true