apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gpu-plugin
spec:
  template:
    spec:
      nodeSelector:
        intel.feature.node.kubernetes.io/gpu: "true"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: intel-gpu-plugin
spec:
  template:
    spec:
      containers:
      - name: intel-gpu-plugin
        args:
        - "-enable-monitoring"
        - "-v=2"