apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-subdir-external-provisioner
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: "{{ .Values.spec.destination.server }}"
  source:
    path: ""
    repoURL: "https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/"
    targetRevision: "4.0.18"
    chart: nfs-subdir-external-provisioner
    helm:
      values: |
        nfs:
          server: "10.0.1.99"
          path: "/rpool/home-cluster"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true